# Minimal, stable Illuminati AI manual generator
# Creates a simple PDF + ZIP package with no external dependencies beyond reportlab

import os
import zipfile
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER

PACKAGE_ZIP_NAME = "Illuminati_AI_Package.zip"
PDF_NAME = "Illuminati_AI_Copy_Master_Manual.pdf"


def build_pdf(output_path: str):
    """Create a very simple Illuminati AI Copy Master manual PDF."""
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        rightMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        name="TitleCenter",
        parent=styles["Title"],
        alignment=TA_CENTER,
        fontSize=20,
        spaceAfter=12,
    )

    subtitle_style = ParagraphStyle(
        name="SubtitleCenter",
        parent=styles["Heading2"],
        alignment=TA_CENTER,
        fontSize=14,
        spaceAfter=18,
    )

    body_style = styles["BodyText"]

    story = []

    # Cover
    story.append(Spacer(1, 1 * inch))
    story.append(Paragraph("Illuminati AI Copy Master", title_style))
    story.append(Paragraph("Strategic SOP & Master Manual (Lite Version)", subtitle_style))
    story.append(Spacer(1, 0.5 * inch))

    story.append(Paragraph(
        "This manual was generated automatically by the Illuminati AI Copy Master system. "
        "It serves as a starter document you can expand with your own notes, funnels, and campaign plans.",
        body_style,
    ))

    story.append(Spacer(1, 0.3 * inch))
    story.append(Paragraph(
        f"Generated on: {datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S')} UTC",
        body_style,
    ))

    story.append(Spacer(1, 0.5 * inch))
    story.append(Paragraph(
        "Suggested Uses:",
        styles["Heading3"],
    ))
    story.append(Paragraph(
        "- Use this as a launchpad for your copy and funnel ideas.<br/>"
        "- Track your offers, angles, and creative tests.<br/>"
        "- Document your best-performing headlines, hooks, and email sequences.",
        body_style,
    ))

    story.append(Spacer(1, 0.5 * inch))
    story.append(Paragraph(
        "Next Steps:",
        styles["Heading3"],
    ))
    story.append(Paragraph(
        "1. Flesh out your core offer and target audience.<br/>"
        "2. Draft headlines and hooks inspired by the masters (Ogilvy, Halbert, Kennedy, etc.).<br/>"
        "3. Build a simple funnel: opt-in page, bridge page, sales page, and thank-you page.<br/>"
        "4. Start small with traffic, track your results, and iterate.",
        body_style,
    ))

    story.append(Spacer(1, 0.75 * inch))
    story.append(Paragraph(
        "Remember: if it doesn’t sell, it isn’t creative. Use this system to stay focused on response.",
        body_style,
    ))

    doc.build(story)


def main():
    # Build PDF
    build_pdf(PDF_NAME)

    # Create ZIP package
    with zipfile.ZipFile(PACKAGE_ZIP_NAME, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.write(PDF_NAME, arcname=PDF_NAME)
        readme_text = (
            "Illuminati AI Copy Master Package (Lite)\n"
            "----------------------------------------\n\n"
            f"PDF: {PDF_NAME}\n\n"
            "This package was generated by the minimal Illuminati AI Copy Master generator.\n"
            "You can expand the manual and generator logic later with more sections, images, and content.\n"
        )
        zf.writestr("README.txt", readme_text)

    print(f"[OK] Created ZIP package: {PACKAGE_ZIP_NAME}")


if __name__ == "__main__":
    main()
